# The name of the workflow, displayed in the "Actions" tab.
name: C++ CI (Multi-Platform)

# Triggers for the workflow (unchanged).
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ##############################################################################
  # Build and Test on Linux (Ubuntu)
  ##############################################################################
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSPSC_QUEUE_BUILD_TESTS=ON
      - name: Build Project
        run: cmake --build build
      - name: Run Tests
        run: ctest --test-dir build --verbose

  ##############################################################################
  # Build and Test on macOS
  ##############################################################################
  build-macos:
    name: Build on macOS
    runs-on: macos-14 # Apple Silicon (ARM)
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install latest Clang via Homebrew
        run: |
          brew install llvm
          echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSPSC_QUEUE_BUILD_TESTS=ON
      - name: Build Project
        run: cmake --build build --config Debug
      - name: Run Tests
        run: |
          cd build
          ctest -C Debug --verbose

  ##############################################################################
  # Build and Test on Windows
  ##############################################################################
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSPSC_QUEUE_BUILD_TESTS=ON
      - name: Build Project
        run: cmake --build build --config Debug
      - name: Run Tests
        run: |
          cd build
          ctest -C Debug --verbose

