# The name of the workflow, displayed in the "Actions" tab.
name: C++ CI (Multi-Platform)

# Triggers for the workflow (unchanged).
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Use a build matrix to run the job on all three major platforms.
    strategy:
      # We must specify a specific macOS runner version. 'macos-13' is Intel,
      # 'macos-14' is Apple Silicon (ARM). Let's test on the latest ARM.
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]

    # Run on the OS specified by the current matrix configuration.
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out repository code.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Install latest LLVM/Clang, but ONLY for the macOS job.
      # We use a different, more reliable community action for this.
      # It correctly handles installing the toolchain and setting the necessary
      # environment variables (CC and CXX) for CMake to find it.
      - name: Install latest Clang on macOS
        if: matrix.os == 'macos-14'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17" # Requesting Clang version 17
          directory: ${{ runner.tool_cache }}/llvm

      # Step 3: Configure the project using CMake.
      # On macOS, CMake will now automatically pick up the new Clang we just
      # installed because the previous step sets the required environment variables.
      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DSPSC_QUEUE_BUILD_TESTS=ON
          -DSPSC_QUEUE_BUILD_EXAMPLES=OFF
          -DSPSC_QUEUE_BUILD_BENCHMARKS=OFF

      # Step 4: Build the project.
      # The '--config Debug' flag is crucial for Visual Studio on Windows and
      # is safely ignored by Makefiles on Linux and macOS.
      - name: Build Project
        run: cmake --build build --config Debug

      # Step 5: Run the tests.
      # The '-C Debug' flag is necessary for ctest with multi-config generators.
      - name: Run Tests
        run: |
          cd build
          ctest -C Debug --verbose

